name: Sync Upstream

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 0 点自动同步一次
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add upstream remote
        run: git remote add upstream https://github.com/riowang88/tvbox-source-aggregator.git

      - name: Fetch upstream
        run: git fetch upstream main

      - name: Merge upstream into your main branch
        run: |
          git config user.name "hq664069"
          git config user.email "lhanzbs855@gmail.com"
          git merge upstream/main --allow-unrelated-histories --no-edit

      - name: Push to your repository
        uses: ad-m/github-push-action@master
        with:
          branch: main
